#! /bin/bash

#use path according to boost installation directory in user machine
export LD_LIBRARY_PATH=../boost_1_78_0/lib:$LD_LIBRARY_PATH

echo "resetting..."
if [ "$1" == "dbg" ]
then 
	gdb ../bin/comp
	exit 0
fi

INPGRAPH=$1
GRAMMAR=$2
NUMPARTITIONS=$3
MEMBUDGET=$4
NUMTHREADS=$5

rm -f $1.[dpv]*

PID=0
trap "{ kill $PID; exit 12; }" EXIT SIGINT SIGQUIT 

echo "RUN ON COMPUTER: "$(hostname) > log/cpp.$MEMBUDGET.$NUMPARTITIONS.output
echo >> log/cpp.$MEMBUDGET.$NUMPARTITIONS.output
echo "RUN ON COMPUTER: "$(hostname) > log/pmap.$MEMBUDGET.$NUMPARTITIONS.output
echo >> log/pmap.$MEMBUDGET.$NUMPARTITIONS.output

../bin/comp numPartitions=$NUMPARTITIONS insertionSort=false alterSchedule=false memBudget=$MEMBUDGET inputGraph=$INPGRAPH grammar=$GRAMMAR numThreads=$NUMTHREADS 

